#!/usr/bin/env python3
"""
Generate the ubi.world ledger explorer pages from signed JSON receipts.

Reads every `{LEDGER_ROOT}/transactions/*.json` and writes three page
types one level up:

    {LEDGER_ROOT}/../index.html                   home dashboard
    {LEDGER_ROOT}/../tx/<id>.html                 one per transaction
    {LEDGER_ROOT}/../handle/<handle>.html         one per handle (urlencoded)
    {LEDGER_ROOT}/../style.css                    design tokens (Tiramisu v3)
    {LEDGER_ROOT}/index.html                      /ledger/ browse page
    {LEDGER_ROOT}/transactions/index.html         /ledger/transactions/ browse page
    {LEDGER_ROOT}/nodes/index.html                /ledger/nodes/ browse page

Idempotent — running twice in a row produces identical bytes. Runs in
under a second for the MVP-scale 9–100 transactions. Designed to be
cron-driven at one-minute cadence (`* * * * *`).

Usage:
    python3 generate_ledger_site.py
    python3 generate_ledger_site.py --ledger-root /home/vrgli/ubi.world/ledger

If --ledger-root isn't passed, falls back to $LEDGER_ROOT then to the
config module's default. Exits 0 even if there are zero transactions —
the home dashboard renders with "No transactions yet".
"""

from __future__ import annotations

import argparse
import html
import json
import logging
import os
import sys
import urllib.parse
from collections import defaultdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Iterable

# Make sure we can import config when run from anywhere.
_HERE = Path(__file__).resolve().parent
_BOT_ROOT = _HERE.parent
if str(_BOT_ROOT) not in sys.path:
    sys.path.insert(0, str(_BOT_ROOT))

try:
    import config  # noqa: E402
except Exception:
    config = None  # type: ignore

logger = logging.getLogger("ubi.gen")

# --------------------------------------------------------------------------- #
# Constants / formatting helpers
# --------------------------------------------------------------------------- #

GENERATED_NOTE = "Generated by tools/generate_ledger_site.py — do not edit by hand."


def fmt_hms(seconds: int) -> str:
    """Render seconds as `HHh MMm SSs` (book spec)."""
    s = int(seconds)
    h, rem = divmod(s, 3600)
    m, sec = divmod(rem, 60)
    return f"{h}h {m:02d}m {sec:02d}s"


def fmt_short(seconds: int) -> str:
    """Compact form for table cells: `1h 23m 04s` or `42m 18s`."""
    s = int(seconds)
    h, rem = divmod(s, 3600)
    m, sec = divmod(rem, 60)
    if h:
        return f"{h}h {m:02d}m {sec:02d}s"
    if m:
        return f"{m}m {sec:02d}s"
    return f"{sec}s"


def fmt_iso_human(iso: str) -> str:
    """`2026-05-22T17:34:25Z` -> `2026-05-22 17:34 UTC`."""
    try:
        dt = datetime.strptime(iso, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except ValueError:
        return iso
    return dt.strftime("%Y-%m-%d %H:%M UTC")


def handle_url(handle: str) -> str:
    """URL-encode a handle for use in /handle/<x>.html links.

    The file on disk has a raw `:` in its name (see `handle_filename`);
    we URL-encode in links so the resulting URL is RFC-clean. Apache
    decodes the `%3A` back to `:` before file lookup, so both encoded
    and raw forms resolve to the same file.
    """
    return urllib.parse.quote(handle, safe="")


def handle_filename(handle: str) -> str:
    """On-disk filename for a handle's detail page.

    Uses the raw handle (with `:`) so Apache's URL-decoding step
    matches the filename. Writing the file with literal `%3A` in the
    name results in 404s because Apache decodes the URL before the
    filesystem lookup.
    """
    # Strip any characters that would actually break a filesystem.
    # Handles legally contain `:` and ASCII alnum; everything else
    # we conservatively percent-encode to be safe.
    safe = []
    for ch in handle:
        if ch.isalnum() or ch in (":", "-", "_", "."):
            safe.append(ch)
        else:
            safe.append("_")
    return "".join(safe) + ".html"


# --------------------------------------------------------------------------- #
# Load + index
# --------------------------------------------------------------------------- #

def load_transactions(tx_dir: Path) -> list[dict]:
    txs = []
    if not tx_dir.exists():
        return txs
    for path in sorted(tx_dir.glob("tx_*.json")):
        try:
            txs.append(json.loads(path.read_text()))
        except Exception as exc:
            logger.warning("skipping malformed %s: %s", path, exc)
    return txs


def index_by_handle(txs: list[dict]) -> dict[str, list[dict]]:
    """Group transactions by handle (both sent and received)."""
    by_handle: dict[str, list[dict]] = defaultdict(list)
    for tx in txs:
        by_handle[tx["from_handle"]].append(tx)
        if tx["to_handle"] != tx["from_handle"]:
            by_handle[tx["to_handle"]].append(tx)
    # Sort each handle's transactions newest-first.
    for h in by_handle:
        by_handle[h].sort(key=lambda t: t.get("timestamp_iso", ""), reverse=True)
    return by_handle


# --------------------------------------------------------------------------- #
# Templates (Tiramisu v3 — top-bar nav, Etherscan-style table, Blue/Red bar)
# --------------------------------------------------------------------------- #

# Inlined CSS. v3 layout from Tiramisu (top-bar pattern, responsive
# table, Blue/Red horizontal bar). Mirrors the .css applied at
# /home/vrgli/ubi.world/style.css on deploy.
STYLE_CSS = r"""
/* ubi.world ledger v3 — top-bar navigation, Etherscan-style responsive tables,
   Blue/Red horizontal bar component. System fonts only. Dark by default. */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root{
  --bg:#16161a;
  --bg-elev:#1d1d23;
  --fg:#e8e6df;
  --muted:#a8a69e;
  --rule:#2c2c33;
  --rule-strong:#3a3a42;
  --accent:#d6c7a8;
  --link:#d6c7a8;
  --link-hover:#ffffff;
  --code-bg:#22222a;
  --row-hover:#1a1a20;
  --row-alt:#191920;
  --blue:#3e80c4;
  --red:#c25a4a;
  --bar-track:#22222a;
  --bar-border:#3a3a42;
}
[data-theme="light"]{
  --bg:#f6f1e3;
  --bg-elev:#efe8d3;
  --fg:#1d1d1b;
  --muted:#5a5a55;
  --rule:#d8d0bb;
  --rule-strong:#bdb39a;
  --accent:#5a4632;
  --link:#5a4632;
  --link-hover:#1d1d1b;
  --code-bg:#ece5cf;
  --row-hover:#ece4ca;
  --row-alt:#f0e9d2;
  --blue:#1e5a96;
  --red:#9a3a2a;
  --bar-track:#e6dcc0;
  --bar-border:#bdb39a;
}

html{scroll-behavior:smooth}
body{
  background:var(--bg);
  color:var(--fg);
  font-family: Georgia, "Iowan Old Style", "Apple Garamond", "Palatino Linotype", "Times New Roman", serif;
  line-height:1.7;
  font-size:18px;
  -webkit-text-size-adjust:100%;
  min-height:100vh;
}

/* TOP BAR */
.topbar{
  position:sticky;top:0;z-index:50;background:var(--bg);
  border-bottom:1px solid var(--rule);
  display:flex;align-items:center;gap:1rem;
  padding:0.55rem 1.2rem;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
}
.topbar-left{display:flex;align-items:center;gap:0.7rem;flex:0 0 auto}
.topbar-flag{display:inline-flex;align-items:center;gap:0.55rem;text-decoration:none;color:var(--fg);line-height:0}
.topbar-flag img{height:24px;width:auto;border-radius:2px;opacity:0.95;display:block}
.topbar-flag .brand{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.78rem;letter-spacing:0.14em;text-transform:uppercase;
  font-weight:700;color:var(--muted);line-height:1;
}
.topbar-flag:hover .brand{color:var(--fg)}
.topbar-title{
  flex:1 1 auto;text-align:center;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.82rem;letter-spacing:0.14em;text-transform:uppercase;
  color:var(--muted);font-weight:700;
}
.topbar-right{display:flex;align-items:center;gap:0.9rem;flex:0 0 auto}
.topbar-eco{display:flex;align-items:center;gap:0.9rem;font-size:0.82rem}
.topbar-eco a{color:var(--link);text-decoration:none;border-bottom:1px solid transparent}
.topbar-eco a:hover{color:var(--link-hover);border-bottom-color:var(--link-hover)}
.theme-toggle{
  background:transparent;border:1px solid var(--rule-strong);color:var(--fg);
  font:inherit;font-size:1.05rem;width:2.1rem;height:2.1rem;padding:0;
  border-radius:50%;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;
}
.theme-toggle:hover{border-color:var(--accent);color:var(--accent)}
.theme-toggle .glyph{font-size:1.1rem;line-height:1}
.menu-toggle{
  display:none;background:transparent;border:1px solid var(--rule-strong);
  color:var(--fg);font:inherit;font-size:0.85rem;padding:0.3rem 0.6rem;
  border-radius:4px;cursor:pointer;line-height:1;
}
.mobile-drawer{
  display:none;position:fixed;top:3rem;left:0;right:0;
  background:var(--bg);border-bottom:1px solid var(--rule);
  padding:0.8rem 1rem;z-index:45;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
.mobile-drawer.open{display:block}
.mobile-drawer a{
  display:block;padding:0.55rem 0.3rem;color:var(--link);
  text-decoration:none;border-bottom:1px solid var(--rule);font-size:0.95rem;
}
.mobile-drawer a:last-child{border-bottom:none}

/* MAIN — full width, centered, generous max-width for tables */
.wrap{max-width:1140px;margin:0 auto;padding:2.4rem 1.6rem 4rem}
.wrap > p, .wrap > h1{max-width:70ch}

.tagline{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.78rem;letter-spacing:0.14em;text-transform:uppercase;
  color:var(--muted);font-weight:700;margin:0 0 1.1rem;
}
h1{
  font-family: Georgia, serif;font-weight:700;font-size:2.1rem;color:var(--fg);
  line-height:1.2;margin:0 0 1.1rem;letter-spacing:-0.01em;
}
h2{
  font-family: Georgia, serif;font-weight:700;font-size:1.5rem;color:var(--fg);
  margin:2.6rem 0 0.9rem;line-height:1.3;padding-bottom:0.4rem;border-bottom:1px solid var(--rule);
}
p{margin:0 0 1.05rem}
a{color:var(--link);text-decoration:none;border-bottom:1px solid transparent}
a:hover{color:var(--link-hover);border-bottom-color:var(--link-hover)}
strong{font-weight:700;color:var(--fg)}
code, .mono{
  font-family: "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;
  font-size:0.88em;color:var(--accent);background:var(--code-bg);
  padding:0.1em 0.35em;border-radius:3px;border:1px solid var(--rule);
}

/* Stats grid */
.stats-grid{
  display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));
  gap:0.9rem;margin:1.4rem 0 0.4rem;
}
.stat-card{
  background:var(--bg-elev);border:1px solid var(--rule);
  border-left:3px solid var(--accent);border-radius:0 4px 4px 0;
  padding:1rem 1.1rem;
}
.stat-card .label{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.74rem;letter-spacing:0.14em;text-transform:uppercase;
  color:var(--muted);font-weight:700;margin-bottom:0.35rem;
}
.stat-card .value{
  font-family: Georgia, serif;font-size:1.55rem;font-weight:700;color:var(--fg);
  line-height:1.15;
}
.stat-card .sub{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.78rem;color:var(--muted);margin-top:0.25rem;
}

/* ETHERSCAN-STYLE TX TABLE.
   Desktop (>=700px): true table.
   Mobile  (<700px):  each row becomes a stacked card; cells use data-label. */
.tx-table-wrap{margin:1rem 0 1.4rem;}
.tx-table{
  width:100%;border-collapse:collapse;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.9rem;
}
.tx-table th, .tx-table td{
  text-align:left;padding:0.6rem 0.75rem;border-bottom:1px solid var(--rule);
  vertical-align:middle;
}
.tx-table th{
  font-size:0.72rem;letter-spacing:0.14em;text-transform:uppercase;
  color:var(--muted);font-weight:700;border-bottom:1px solid var(--rule-strong);
  background:var(--bg-elev);
}
.tx-table tbody tr:nth-child(even) td{background:var(--row-alt)}
.tx-table tbody tr:hover td{background:var(--row-hover)}
.tx-table td.amount{font-family: "SF Mono", Menlo, Consolas, monospace;color:var(--fg);white-space:nowrap}
.tx-table td.time{font-family: "SF Mono", Menlo, Consolas, monospace;color:var(--muted);white-space:nowrap;font-size:0.85rem}
.tx-table td.handle{font-family: "SF Mono", Menlo, Consolas, monospace;font-size:0.88rem}
.tx-table td.node{font-family: "SF Mono", Menlo, Consolas, monospace;color:var(--muted);font-size:0.85rem;white-space:nowrap}

/* BLUE / RED HORIZONTAL BAR — replaces the old circle/percentage pill.
   <span class="br-bar" data-blue="80" aria-label="80% blue, 20% red">
     <span class="br-fill br-blue" style="width:80%"></span>
     <span class="br-fill br-red"  style="width:20%"></span>
   </span>
   <span class="br-num">80% blue</span>
*/
.br-cell{display:inline-flex;align-items:center;gap:0.5rem;white-space:nowrap}
.br-bar{
  display:inline-flex;width:80px;height:10px;
  border:1px solid var(--bar-border);border-radius:5px;
  background:var(--bar-track);overflow:hidden;flex:0 0 auto;
}
.br-fill{display:block;height:100%}
.br-fill.br-blue{background:var(--blue)}
.br-fill.br-red{background:var(--red)}
.br-num{
  font-family: "SF Mono", Menlo, Consolas, monospace;font-size:0.82rem;
  color:var(--blue);font-weight:600;
}
.br-num.red-leaning{color:var(--red)}
/* Larger variant for detail pages */
.br-bar.br-bar-lg{width:160px;height:14px;border-radius:7px}
.br-bar-lg + .br-num{font-size:1rem}

/* Key/value list (tx detail) */
.kv{
  display:grid;grid-template-columns:max-content 1fr;column-gap:1.4rem;row-gap:0.55rem;
  margin:1rem 0 0;font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.92rem;
}
.kv dt{
  font-size:0.72rem;letter-spacing:0.12em;text-transform:uppercase;
  color:var(--muted);font-weight:700;padding-top:0.15rem;
}
.kv dd{margin:0;color:var(--fg);font-family: "SF Mono", Menlo, Consolas, monospace;word-break:break-all}
.kv dd.serif{font-family: Georgia, serif}

.sig-block{
  margin-top:0.4rem;padding:0.7rem 0.9rem;background:var(--code-bg);
  border:1px solid var(--rule);border-radius:4px;
  font-family: "SF Mono", Menlo, Consolas, monospace;font-size:0.8rem;
  color:var(--muted);word-break:break-all;
}
.sig-toggle{
  background:none;border:none;color:var(--link);cursor:pointer;
  font:inherit;font-size:0.78rem;padding:0;margin-left:0.4rem;
  border-bottom:1px solid var(--rule-strong);
}

/* Crumbs (for /ledger/, /ledger/transactions/, /ledger/nodes/ subpages) */
.crumbs{
  font-family: "SF Mono", Menlo, Consolas, monospace;font-size:0.82rem;
  color:var(--muted);margin-bottom:1.5rem;letter-spacing:0.04em;
}
.crumbs a{color:var(--muted);text-decoration:none;border-bottom:1px dotted var(--muted)}
.crumbs a:hover{color:var(--link-hover);border-bottom-color:var(--link-hover)}

.notice{
  background:var(--bg-elev);border:1px solid var(--rule);
  border-left:3px solid var(--accent);border-radius:0 4px 4px 0;
  padding:1.1rem 1.3rem;margin:1.5rem 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.92rem;line-height:1.55;
}
.notice strong{color:var(--accent);display:block;font-size:0.74rem;
  letter-spacing:0.14em;text-transform:uppercase;margin-bottom:0.5rem;}

footer{
  border-top:1px solid var(--rule);padding:1.1rem 0 0;margin-top:3rem;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.78rem;color:var(--muted);letter-spacing:0.05em;
}

/* Mobile breakpoint — top bar collapses, tables become cards */
@media (max-width:780px){
  .topbar{padding:0.45rem 0.8rem;gap:0.5rem}
  .topbar-title{display:none}
  .topbar-eco{display:none}
  .menu-toggle{display:inline-block}
  body{font-size:17px}
  .wrap{padding:1.6rem 1rem 3rem}
  h1{font-size:1.7rem}
  h2{font-size:1.25rem}
  .kv{grid-template-columns:1fr}
  .kv dt{padding-top:0.6rem}
}

/* Etherscan-style card layout for tables on mobile */
@media (max-width:700px){
  .tx-table{display:block;font-size:0.92rem}
  .tx-table thead{display:none}
  .tx-table tbody{display:block}
  .tx-table tbody tr{
    display:block;
    background:var(--bg-elev);
    border:1px solid var(--rule);
    border-radius:5px;
    margin-bottom:0.7rem;
    padding:0.6rem 0.8rem;
  }
  .tx-table tbody tr:nth-child(even) td{background:transparent}
  .tx-table tbody tr:hover td{background:transparent}
  .tx-table tbody td{
    display:flex;
    align-items:flex-start;
    gap:0.8rem;
    padding:0.35rem 0;
    border-bottom:1px dashed var(--rule);
    white-space:normal;
    word-break:break-word;
  }
  .tx-table tbody td:last-child{border-bottom:none}
  .tx-table tbody td::before{
    content: attr(data-label);
    flex:0 0 6.5rem;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    font-size:0.68rem;
    letter-spacing:0.12em;
    text-transform:uppercase;
    color:var(--muted);
    font-weight:700;
    padding-top:0.15rem;
  }
  .tx-table tbody td.time{font-size:0.84rem}
  .br-bar{width:60px;height:9px}
  .br-num{font-size:0.78rem}
}
"""

# Boot-time theme glue + chrome controls. Same as Tiramisu's deployed
# index.html so the toggle and mobile drawer behave identically.
THEME_SCRIPT = """<script>(function(){try{var t=localStorage.getItem('ubi-theme');document.documentElement.setAttribute('data-theme',t==='light'?'light':'dark');}catch(e){document.documentElement.setAttribute('data-theme','dark');}})();</script>"""

CHROME_SCRIPT = """<script>
(function(){
  var root=document.documentElement;
  function applyTheme(t){root.setAttribute('data-theme',t);var b=document.getElementById('themeBtn');if(b){var dark=t==='dark';b.setAttribute('aria-pressed',dark?'true':'false');b.setAttribute('title',dark?'Switch to light mode':'Switch to dark mode');b.innerHTML='<span class="glyph" aria-hidden="true">'+(dark?'\\u2600':'\\u263E')+'</span>';}}
  function currentTheme(){try{var v=localStorage.getItem('ubi-theme');return v==='light'?'light':'dark';}catch(e){return 'dark';}}
  applyTheme(currentTheme());
  var btn=document.getElementById('themeBtn');
  if(btn){btn.addEventListener('click',function(){var next=currentTheme()==='dark'?'light':'dark';try{localStorage.setItem('ubi-theme',next);}catch(e){}applyTheme(next);});}
  var mbtn=document.getElementById('menuBtn');
  var drawer=document.getElementById('mobileDrawer');
  if(mbtn&&drawer){mbtn.addEventListener('click',function(){var open=drawer.classList.toggle('open');mbtn.setAttribute('aria-expanded',open?'true':'false');});}
  var sigToggle=document.getElementById('sigToggle');
  if(sigToggle){sigToggle.addEventListener('click',function(){var full=document.getElementById('sigFull');var trunc=document.getElementById('sigTrunc');var showing=full.style.display!=='none';full.style.display=showing?'none':'block';trunc.style.display=showing?'inline':'none';sigToggle.textContent=showing?'show full':'hide';});}
})();
</script>"""


def _topbar_html(title_label: str) -> str:
    """Sticky top bar — replaces the old left sidebar.

    `title_label` is the small uppercase centred label (e.g. 'Public Ledger',
    'Transaction', 'Handle'). The flag, ecosystem links, theme toggle and
    mobile drawer are always present.
    """
    return f"""<header class="topbar" role="banner">
  <div class="topbar-left">
    <a class="topbar-flag" href="/" aria-label="Time for UBI home">
      <img src="https://ubi.vision/UBI-Flag/UBI-Flag-120x100px.png" alt="UBI flag" width="29" height="22">
      <span class="brand">Time for UBI</span>
    </a>
  </div>
  <div class="topbar-title">{html.escape(title_label)}</div>
  <div class="topbar-right">
    <nav class="topbar-eco" aria-label="Ecosystem">
      <a href="https://ubi.vision">Spec</a>
      <a href="https://ubi.education">Book</a>
      <a href="https://ubi.world">Ledger</a>
    </nav>
    <button class="theme-toggle" id="themeBtn" type="button" aria-label="Toggle dark or light mode" aria-pressed="true" title="Toggle dark / light"><span class="glyph" aria-hidden="true">&#9728;</span></button>
    <button class="menu-toggle" id="menuBtn" type="button" aria-label="Open menu" aria-expanded="false">&#9776;</button>
  </div>
</header>

<nav class="mobile-drawer" id="mobileDrawer" aria-label="Ecosystem (mobile)">
  <a href="https://ubi.vision">Spec &rarr; ubi.vision</a>
  <a href="https://ubi.education">Book &rarr; ubi.education</a>
  <a href="https://ubi.world">Ledger &rarr; ubi.world</a>
  <a href="/ledger/">Raw signed JSONs</a>
</nav>
"""


# Kept for backwards-compat callers that referenced the old name — returns empty.
def _sidebar_html(active: str = "home") -> str:
    return ""


def _page_shell(title: str, body: str, active: str = "home", topbar_label: str = "Public Ledger") -> str:
    """Wrap a page body in the v3 top-bar shell."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<meta name="description" content="ubi.world — public ledger of Time for UBI transactions.">
<link rel="stylesheet" href="/style.css">
{THEME_SCRIPT}
</head>
<body>

{_topbar_html(topbar_label)}

<main class="wrap">
{body}
<footer>ubi.world &middot; public ledger &middot; signed by participating nodes &middot; generated {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}</footer>
</main>

{CHROME_SCRIPT}
</body>
</html>
"""


# --------------------------------------------------------------------------- #
# Page builders
# --------------------------------------------------------------------------- #

def _tx_row(tx: dict) -> str:
    """Emit one <tr> for the Etherscan-style transaction table.

    Every <td> carries a data-label attribute so the mobile (<700px) CSS
    can flip rows into stacked cards via ::before. The Blue/Red column
    uses the br-cell + br-bar + br-num pattern (Tiramisu v3 patch).
    """
    tx_id = tx["id"]
    ts = fmt_iso_human(tx.get("timestamp_iso", ""))
    frm = tx["from_handle"]
    to = tx["to_handle"]
    amount = fmt_short(tx["amount_seconds"])
    blue = tx.get("blue_pct", 100)
    red = 100 - blue
    node = tx.get("from_node", "")
    return (
        f"<tr>"
        f"<td class=\"time\" data-label=\"Time\">{html.escape(ts)}</td>"
        f"<td class=\"handle\" data-label=\"From\"><a href=\"/handle/{handle_url(frm)}.html\">{html.escape(frm)}</a></td>"
        f"<td class=\"handle\" data-label=\"To\"><a href=\"/handle/{handle_url(to)}.html\">{html.escape(to)}</a></td>"
        f"<td class=\"amount\" data-label=\"Amount\"><a href=\"/tx/{tx_id}.html\">{html.escape(amount)}</a></td>"
        f"<td data-label=\"Blue / Red\">"
        f"<span class=\"br-cell\">"
        f"<span class=\"br-bar\" aria-label=\"{blue}% blue, {red}% red\">"
        f"<span class=\"br-fill br-blue\" style=\"width:{blue}%\"></span>"
        f"<span class=\"br-fill br-red\" style=\"width:{red}%\"></span>"
        f"</span>"
        f"<span class=\"br-num\">{blue}% blue</span>"
        f"</span>"
        f"</td>"
        f"<td class=\"node\" data-label=\"Node\">{html.escape(node)}</td>"
        f"</tr>"
    )


def build_home(txs: list[dict], handles: Iterable[str]) -> str:
    """Home dashboard with stats block + latest 50 table."""
    total_tx = len(txs)
    total_handles = len(set(handles))

    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(hours=24)

    minted_24h = 0
    largest_24h = 0
    for tx in txs:
        try:
            ts = datetime.strptime(tx["timestamp_iso"], "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
        except Exception:
            continue
        if ts >= cutoff:
            minted_24h += tx["amount_seconds"]
            if tx["amount_seconds"] > largest_24h:
                largest_24h = tx["amount_seconds"]

    # Build the table — newest first, cap at 50.
    txs_sorted = sorted(txs, key=lambda t: t.get("timestamp_iso", ""), reverse=True)
    latest = txs_sorted[:50]

    if latest:
        table_rows = "\n".join(_tx_row(t) for t in latest)
        table = f"""<div class="tx-table-wrap">
<table class="tx-table">
<thead>
<tr><th>Time (UTC)</th><th>From</th><th>To</th><th>Amount</th><th>Blue / Red</th><th>Node</th></tr>
</thead>
<tbody>
{table_rows}
</tbody>
</table>
</div>"""
    else:
        table = "<p style=\"color:var(--muted)\">No transactions yet. The ledger fills as nodes come online.</p>"

    stats_html = f"""<div class="stats-grid">
  <div class="stat-card">
    <div class="label">Total transactions</div>
    <div class="value">{total_tx:,}</div>
    <div class="sub">since inception</div>
  </div>
  <div class="stat-card">
    <div class="label">Active handles</div>
    <div class="value">{total_handles:,}</div>
    <div class="sub">handles that have sent or received</div>
  </div>
  <div class="stat-card">
    <div class="label">Time moved (last 24h)</div>
    <div class="value">{fmt_short(minted_24h)}</div>
    <div class="sub">across all recorded transfers</div>
  </div>
  <div class="stat-card">
    <div class="label">Largest transfer (24h)</div>
    <div class="value">{fmt_short(largest_24h)}</div>
    <div class="sub">single signed receipt</div>
  </div>
</div>"""

    body = f"""<p class="tagline">Public ledger &middot; Time for UBI</p>
<h1>The time economy, transaction by transaction.</h1>
<p>
  Every transfer on the Time for UBI federation is signed by the node that recorded it,
  then mirrored here. The raw JSONs live at <a href="/ledger/">ubi.world/ledger</a>.
  This page renders them.
</p>

<h2>Network at a glance</h2>
{stats_html}

<h2>Latest transactions</h2>
{table}

<h2>How it works</h2>
<p>
  When a transaction completes on a participating node, that node signs the
  receipt with its Ed25519 private key and writes the signed JSON to its slice
  of <code>/ledger/transactions/</code>. A small generator re-renders this page
  every minute. Tampering would break the signature; anyone can verify offline
  using the signing node's public key.
</p>
<p>
  Read the full <a href="https://ubi.vision">specification at ubi.vision</a>, or
  the long-form rationale in the book at <a href="https://ubi.education">ubi.education</a>.
</p>
"""
    return _page_shell("ubi.world — public ledger of Time for UBI", body, active="home", topbar_label="Public Ledger")


def build_tx_detail(tx: dict) -> str:
    tx_id = tx["id"]
    amount = fmt_hms(tx["amount_seconds"])
    blue = tx.get("blue_pct", 100)
    red = 100 - blue
    ts = fmt_iso_human(tx.get("timestamp_iso", ""))
    frm = tx["from_handle"]
    to = tx["to_handle"]
    sig = tx.get("node_signature", "")
    sig_trunc = (sig[:16] + "…" + sig[-16:]) if len(sig) > 40 else sig

    body = f"""<p class="tagline">Transaction &middot; {html.escape(tx_id)}</p>
<h1>{html.escape(amount)} &mdash; {html.escape(frm)} <span style="color:var(--muted)">&rarr;</span> {html.escape(to)}</h1>
<p style="color:var(--muted)">{html.escape(ts)} &middot; signed by <code>{html.escape(tx.get("signing_node_domain", ""))}</code></p>

<h2>Blue / Red signal</h2>
<div style="display:flex;align-items:center;gap:0.9rem;margin:0.6rem 0 1.6rem">
  <span class="br-bar br-bar-lg" aria-label="{blue}% blue, {red}% red">
    <span class="br-fill br-blue" style="width:{blue}%"></span>
    <span class="br-fill br-red"  style="width:{red}%"></span>
  </span>
  <span class="br-num">{blue}% blue &middot; {red}% red</span>
</div>

<h2>Receipt</h2>
<dl class="kv">
  <dt>Transaction ID</dt>           <dd>{html.escape(tx_id)}</dd>
  <dt>Type</dt>                     <dd>{html.escape(tx.get("type", "transfer"))}</dd>
  <dt>From</dt>                     <dd><a href="/handle/{handle_url(frm)}.html">{html.escape(frm)}</a></dd>
  <dt>To</dt>                       <dd><a href="/handle/{handle_url(to)}.html">{html.escape(to)}</a></dd>
  <dt>From node</dt>                <dd>{html.escape(tx.get("from_node", ""))}</dd>
  <dt>To node</dt>                  <dd>{html.escape(tx.get("to_node", ""))}</dd>
  <dt>Amount</dt>                   <dd>{html.escape(amount)} <span style="color:var(--muted)">({tx["amount_seconds"]:,} seconds)</span></dd>
  <dt>Blue / Red</dt>               <dd>blue {blue}% &middot; red {red}%</dd>
  <dt>Timestamp (UTC)</dt>          <dd>{html.escape(ts)}</dd>
  <dt>Signed at</dt>                <dd>{html.escape(fmt_iso_human(tx.get("signed_at_iso", "")))}</dd>
  <dt>Signing node</dt>             <dd>{html.escape(tx.get("signing_node_domain", ""))}</dd>
  <dt>Node fingerprint</dt>         <dd>{html.escape(tx.get("signing_node_public_key_fingerprint", ""))}</dd>
  <dt>Ledger format</dt>            <dd>{html.escape(tx.get("ledger_format_version", ""))}</dd>
</dl>

<h2>Signature
  <span id="sigTrunc" style="font-family:'SF Mono',Menlo,monospace;font-size:0.78rem;color:var(--muted);font-weight:400">
    {html.escape(sig_trunc)}
    <button id="sigToggle" class="sig-toggle" type="button">show full</button>
  </span>
</h2>
<div id="sigFull" class="sig-block" style="display:none">{html.escape(sig)}</div>

<p style="margin-top:1.2rem">
  Raw signed JSON: <a href="/ledger/transactions/{html.escape(tx_id)}.json">/ledger/transactions/{html.escape(tx_id)}.json</a>
</p>
"""
    return _page_shell(f"{tx_id} — ubi.world", body, active="tx", topbar_label="Transaction")


def build_handle_detail(handle: str, txs_for_handle: list[dict]) -> str:
    """Handle page — sent / received lists + simple totals."""
    sent = [t for t in txs_for_handle if t["from_handle"] == handle]
    received = [t for t in txs_for_handle if t["to_handle"] == handle and t["from_handle"] != handle]

    total_sent = sum(t["amount_seconds"] for t in sent)
    total_received = sum(t["amount_seconds"] for t in received)

    # Aggregate blue/red across all transfers (sent — that's where the
    # receiver assigned the rating; received doesn't carry this handle's
    # own rating).
    rated = sent  # sender's transactions carry the rating recipient gave
    if rated:
        avg_blue_int = round(sum(t.get("blue_pct", 100) for t in rated) / len(rated))
    else:
        avg_blue_int = 0
    avg_red_int = 100 - avg_blue_int
    has_rating = bool(rated)

    def tx_table(rows: list[dict], empty_msg: str) -> str:
        if not rows:
            return f"<p style=\"color:var(--muted)\">{empty_msg}</p>"
        body = "\n".join(_tx_row(t) for t in rows)
        return f"""<div class="tx-table-wrap">
<table class="tx-table">
<thead><tr><th>Time (UTC)</th><th>From</th><th>To</th><th>Amount</th><th>Blue / Red</th><th>Node</th></tr></thead>
<tbody>{body}</tbody>
</table>
</div>"""

    if has_rating:
        br_card_body = (
            f'<div style="display:flex;align-items:center;gap:0.6rem;margin-top:0.35rem">'
            f'<span class="br-bar br-bar-lg" aria-label="{avg_blue_int}% blue, {avg_red_int}% red">'
            f'<span class="br-fill br-blue" style="width:{avg_blue_int}%"></span>'
            f'<span class="br-fill br-red"  style="width:{avg_red_int}%"></span>'
            f'</span>'
            f'<span class="br-num">{avg_blue_int}%</span>'
            f'</div>'
        )
    else:
        br_card_body = '<div class="value" style="font-size:1.1rem;color:var(--muted)">n/a</div>'

    stats = f"""<div class="stats-grid">
  <div class="stat-card">
    <div class="label">Total received</div>
    <div class="value">{fmt_short(total_received)}</div>
    <div class="sub">{len(received)} transfer{"s" if len(received)!=1 else ""}</div>
  </div>
  <div class="stat-card">
    <div class="label">Total sent</div>
    <div class="value">{fmt_short(total_sent)}</div>
    <div class="sub">{len(sent)} transfer{"s" if len(sent)!=1 else ""}</div>
  </div>
  <div class="stat-card">
    <div class="label">Blue / Red (outgoing)</div>
    {br_card_body}
    <div class="sub">how recipients rated this handle</div>
  </div>
</div>"""

    body = f"""<p class="tagline">Handle</p>
<h1><span style="font-family: 'SF Mono', Menlo, Consolas, monospace; color:var(--accent)">{html.escape(handle)}</span></h1>
<p>Public history of every transaction this handle is party to. Privacy is by design 100% public — every handle's full history is visible without opt-in.</p>

<h2>At a glance</h2>
{stats}

<h2>Received <span style="font-weight:400;font-size:1rem;color:var(--muted)">({len(received)})</span></h2>
{tx_table(received, "No incoming transfers yet.")}

<h2>Sent <span style="font-weight:400;font-size:1rem;color:var(--muted)">({len(sent)})</span></h2>
{tx_table(sent, "No outgoing transfers yet.")}
"""
    return _page_shell(f"{handle} — ubi.world", body, active="handle", topbar_label="Handle")



# --------------------------------------------------------------------------- #
# /ledger/ browse pages — top-bar shell + family palette.
# Replaces the Google-Fonts CDN island that Stefano flagged as "unstyled".
# --------------------------------------------------------------------------- #

def build_ledger_root_browse() -> str:
    """Top-level /ledger/ browse page — describes structure of the raw tree."""
    body = """<p class="crumbs"><a href="/">ubi.world</a> / ledger</p>
<p class="tagline">Public ledger</p>
<h1>Federated UBI transactions, openly mirrored.</h1>
<p>
  This directory holds the raw signed JSON transactions and node records
  for the Time for UBI federation. The human-readable rendering lives at
  <a href="/">ubi.world</a>; this tree is for verifiers and archivists.
</p>

<div class="notice">
  <strong>What lives here</strong>
  <code>/ledger/transactions/</code> — one JSON file per signed transaction.<br>
  <code>/ledger/nodes/</code> — one JSON file per participating node.<br>
  <code>/ledger/README.txt</code> — short explainer for anyone browsing the raw tree.
</div>

<h2>Reading the ledger directly</h2>
<p>
  Every file is plain text. You can fetch the directories directly:
</p>
<p>
  <a href="/ledger/transactions/">/ledger/transactions/</a> &middot;
  <a href="/ledger/nodes/">/ledger/nodes/</a> &middot;
  <a href="/ledger/README.txt">/ledger/README.txt</a>
</p>

<h2>How transactions get here</h2>
<p>
  Participating nodes sign each transfer with their Ed25519 private key
  and write the signed JSON to their slice of <code>/ledger/transactions/</code>.
  Tampering would break the signature; anyone can verify offline using the
  signing node's public key. See the spec at
  <a href="https://ubi.vision/">ubi.vision</a> for the signature scheme.
</p>
<p>
  ubi.world is a mirror, not a router. If this site disappeared, the
  transactions would still exist in the records of the nodes that signed
  them. Anyone with a copy of this directory can host a duplicate mirror.
</p>

<p style="margin-top:2rem">
  <a href="/">&larr; back to ubi.world</a>
</p>
"""
    return _page_shell("ubi.world/ledger — public ledger of Time for UBI", body, active="ledger", topbar_label="Public Ledger")


def build_ledger_transactions_browse() -> str:
    """`/ledger/transactions/` browse page — describes the on-disk tx tree."""
    body = """<p class="crumbs"><a href="/">ubi.world</a> / <a href="/ledger/">ledger</a> / transactions</p>
<p class="tagline">Public ledger / transactions</p>
<h1>Signed transaction records.</h1>
<p>
  Each file in this directory is a single signed JSON transaction published
  by a participating node. File names are numbered so anyone can
  independently verify integrity.
</p>

<div class="notice">
  <strong>Status</strong>
  This is the raw on-disk listing. For the human-readable transaction
  list, see <a href="/">ubi.world</a>. For the signed JSON of one
  specific transaction, click through Apache's directory listing below.
</div>

<p>
  Signature scheme and verification rules are documented in the spec at
  <a href="https://ubi.vision/">ubi.vision</a>.
</p>

<p style="margin-top:2rem">
  <a href="/ledger/">&larr; back to /ledger/</a>
</p>
"""
    return _page_shell("ubi.world/ledger/transactions — Public Ledger Browser", body, active="ledger", topbar_label="Public Ledger")


def build_ledger_nodes_browse() -> str:
    """`/ledger/nodes/` browse page — describes the node directory."""
    body = """<p class="crumbs"><a href="/">ubi.world</a> / <a href="/ledger/">ledger</a> / nodes</p>
<p class="tagline">Public ledger / nodes</p>
<h1>Participating node directory.</h1>
<p>
  Each file in this directory is a small JSON record for one node on the
  federation: domain, operator handle, public key, and the date it first
  announced itself. Any verifier can use these public keys to check the
  signatures on transactions in
  <a href="/ledger/transactions/">/ledger/transactions/</a>.
</p>

<div class="notice">
  <strong>Status</strong>
  Empty until federation Stage 2b ships. The first records will appear as
  nodes complete the announcement protocol.
</div>

<p>
  Node announcement format and key rotation rules are documented in the
  spec at <a href="https://ubi.vision/">ubi.vision</a>.
</p>

<p style="margin-top:2rem">
  <a href="/ledger/">&larr; back to /ledger/</a>
</p>
"""
    return _page_shell("ubi.world/ledger/nodes — Public Ledger Browser", body, active="ledger", topbar_label="Public Ledger")


# --------------------------------------------------------------------------- #
# Atomic write helper
# --------------------------------------------------------------------------- #

def _atomic_write(path: Path, content: str) -> bool:
    """Write `content` to `path`, only touching the file if bytes differ.

    Returns True if the file was (re)written. This keeps the generator
    idempotent and avoids needlessly bumping mtimes (which would
    confuse Cloudflare's origin freshness checks).
    """
    new_bytes = content.encode("utf-8")
    if path.exists():
        try:
            if path.read_bytes() == new_bytes:
                return False
        except OSError:
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_bytes(new_bytes)
    os.replace(tmp, path)
    return True


# --------------------------------------------------------------------------- #
# Main entry point
# --------------------------------------------------------------------------- #

def generate(ledger_root: Path) -> dict:
    """Re-render all pages. `ledger_root` is the directory that contains
    `transactions/`; the output goes to its parent."""
    out_root = ledger_root.parent
    tx_dir = ledger_root / "transactions"

    txs = load_transactions(tx_dir)
    by_handle = index_by_handle(txs)
    all_handles = list(by_handle.keys())

    counts = {"home": 0, "tx": 0, "handle": 0, "style": 0, "browse": 0, "txs_loaded": len(txs)}

    # style.css
    if _atomic_write(out_root / "style.css", STYLE_CSS.lstrip()):
        counts["style"] = 1

    # Home
    if _atomic_write(out_root / "index.html", build_home(txs, all_handles)):
        counts["home"] = 1

    # Transaction detail pages
    tx_out = out_root / "tx"
    for tx in txs:
        if _atomic_write(tx_out / f"{tx['id']}.html", build_tx_detail(tx)):
            counts["tx"] += 1

    # Handle detail pages — raw `:` on disk (Apache decodes %3A before
    # looking up the file, so encoded filenames 404). Links in the
    # generated HTML are URL-encoded so the *URLs* stay RFC-clean.
    handle_out = out_root / "handle"
    for handle, handle_txs in by_handle.items():
        if _atomic_write(handle_out / handle_filename(handle), build_handle_detail(handle, handle_txs)):
            counts["handle"] += 1

    # /ledger/ browse pages — replace the old Google-Fonts island with the
    # family top-bar shell so they match the rest of the site.
    counts["browse"] = 0
    if _atomic_write(ledger_root / "index.html", build_ledger_root_browse()):
        counts["browse"] += 1
    if _atomic_write(ledger_root / "transactions" / "index.html", build_ledger_transactions_browse()):
        counts["browse"] += 1
    if _atomic_write(ledger_root / "nodes" / "index.html", build_ledger_nodes_browse()):
        counts["browse"] += 1

    return counts


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="ubi.world static-site generator")
    parser.add_argument("--ledger-root", default=None, help="root of the ledger (parent of transactions/)")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s  %(levelname)s  %(message)s",
    )

    root = args.ledger_root or os.environ.get("LEDGER_ROOT") or (getattr(config, "LEDGER_ROOT", None) if config else None)
    if not root:
        print("error: --ledger-root not given and LEDGER_ROOT not set", file=sys.stderr)
        return 2

    root_path = Path(root).expanduser()
    if not root_path.exists():
        print(f"error: ledger root does not exist: {root_path}", file=sys.stderr)
        return 2

    counts = generate(root_path)
    logger.info("generated: %s", counts)
    return 0


if __name__ == "__main__":
    sys.exit(main())
